### ISSUE TITLE
Installation/update docs

### ISSUE THREAD

**Issue by html5cat** [Nexmo/nexmo-nodered#12]
Would be nice to have docs on installing/updating the module in Node-red.
(I can't find a way to add latest 3.0 version)

**Comment by sammachin** [comment]
Yeah currently the 3.0 version is tagged as beta in NPM and node-red can't install stuff thats tagged, you have to install it from the command line into your `~/.node-red` folder.
Therefore there doesn't seem much point in releasing a beta to NPM we either have beta users install the latest version directly from github `npm install git+https://git@github.com/nexmo/nexmo-nodered.git` or wait until we're ready to push out 3.0 and replace the current 2.0 version thats on there (which we didn't write)

**Comment by sammachin** [comment]
have added some instructions to the README and will expand on that as we get feedback from the community, PR's to that doc most welcom
