### ISSUE TITLE
Configuration a bit confusing

### ISSUE THREAD

**Issue by html5cat** [Nexmo/nexmo-nodered#13]
First time looking at this screen, I was a bit confused what goes into the fields:
![screen shot 2019-01-09 at 10 00 43 pm](https://user-images.githubusercontent.com/823890/50949482-3ed16300-145b-11e9-8ec7-42e7b067a3ac.png)
Would be nice to have recipient name and number closer imho, also maybe rename to "Sender #", "Recipient #"?

"Configuration" drops to second line with the icon:
![screen shot 2019-01-09 at 10 00 21 pm](https://user-images.githubusercontent.com/823890/50949478-3aa54580-145b-11e9-9e3f-a7bcc8b5f8ba.png)

**Comment by sammachin** [comment]
Thats the old 2.0 version that someone else wrote
