### ISSUE TITLE
Error installing module in IBM's bluemix node-RED

### ISSUE THREAD

**Issue by emilianop11** [Nexmo/nexmo-nodered#19]
<img width="914" alt="captura" src="https://user-images.githubusercontent.com/9683228/52595076-c7ad3700-2e2b-11e9-87f1-8dcfdffa4e42.PNG">

As seen on the image above, the installation of the module fails on IBM's bluemix node-red. No descriptive message is shown in the console.

To reproduce click on the hamburguer menu in the top right corner, click on "Manage Palette". On the "Install" tab search for the nexmo module and just click "install"

**Comment by sammachin** [comment]
this seems to be an out of memory issue with the IBM cloud foundry instance, the default only has 256MB, I upped mine to 384 and it installed fine.
It seems to now be sitting at 120MB of memory in use so I think its just NPM eating all the RAM, will try and do some profiling of the nexmo-node package to see what that uses to install.
